Adding the script to allow for disconnected mode by modifying the image digest field

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -1,139 +1,195 @@
 name: push
-on: 
+on:
   push:
     branches:
       - master
       - main
-    tags:        
+    tags:
       - v*
-    
+
 jobs:
   build:
     runs-on: ubuntu-latest
     name: build
     steps:
+      - name: set repo name
+        shell: bash
+        env:
+          QUAY_REGISTRY: ${{ secrets.QUAY_REGISTRY }}
+        run: |
+          DEFAULT_QUAY_REGISTRY=${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)
+          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" |tee -a $GITHUB_ENV
+          echo "QUAY_REGISTRY=${QUAY_REGISTRY:-$DEFAULT_QUAY_REGISTRY}" |tee -a $GITHUB_ENV
 
-    - name: set repo name
-      shell: bash
-      run: | 
-        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV    
+      - name: Set up Go 1.x
+        uses: actions/setup-go@v2
+        with:
+          go-version: ^1.14
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v2
 
-    - name: Set up Go 1.x
-      uses: actions/setup-go@v2
-      with:
-        go-version: ^1.15
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
+      - name: Download operator sdk
+        shell: bash
+        env:
+          RELEASE_VERSION: v1.5.0
+        run: |
+          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
+          chmod +x operator-sdk_linux_amd64
+          mkdir ${HOME}/bin
+          mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
+          echo "${HOME}/bin" |tee -a $GITHUB_PATH
 
-    - name: Download operator sdk
-      shell: bash
-      env:
-        RELEASE_VERSION: v1.5.0
-      run: | 
-        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
-        chmod +x operator-sdk_linux_amd64
-        mkdir ${HOME}/bin
-        mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
-        echo "${HOME}/bin" >> $GITHUB_PATH
+      - name: Install yq
+        shell: bash
+        env:
+          YQ_VERSION: 3.4.0
+        run: |
+          sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
 
-    - name: Get the version for tags
-      id: get_version1
-      if: "startsWith(github.ref, 'refs/tags')"
-      shell: bash
-      run: |
-        echo "OPERATOR_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
-        echo "BUNDLE_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
-        export TAG=${GITHUB_REF/refs\/tags\//}
-        echo "BUNDLE_VERSION=${TAG:1}" >> $GITHUB_ENV
-        export SEMVER_COMPLIANT=$(echo ${TAG:1} | egrep '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-])(?:\.(?:0|[1-9]\d|\d*[a-zA-Z-][0-9a-zA-Z-]))))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')
-        if [ -z "$SEMVER_COMPLIANT" ]; then   echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}"; exit 1; fi
+      - name: Download compatible Helm version
+        shell: bash
+        env:
+          HELM_VERSION: v3.3.0
+        run: |
+          curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar vxz \
+              && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
+              && rm -vrf linux-amd64
 
+      - name: Get the version for tags
+        id: get_version1
+        if: "startsWith(github.ref, 'refs/tags')"
+        shell: bash
+        run: |
+          echo "OPERATOR_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" |tee -a $GITHUB_ENV
+          echo "BUNDLE_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" |tee -a $GITHUB_ENV
+          export TAG=${GITHUB_REF/refs\/tags\//}
+          echo "BUNDLE_VERSION=${TAG:1}" |tee -a $GITHUB_ENV
+          # Checking Semantic Versioning using official guide here: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string .
+          SEMANTICREGEX='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
+          export SEMVER_COMPLIANT=$(echo ${TAG:1} | grep -Po $SEMANTICREGEX)
+          if [ -z "$SEMVER_COMPLIANT" ]; then   echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}"; exit 1; fi
+      - name: Get most recent tag
+        uses: actions-ecosystem/action-get-latest-tag@v1
+        id: get-latest-tag
+        if: "! startsWith(github.ref, 'refs/tags')"
+        with:
+          semver_only: true
 
+      - uses: actions-ecosystem/action-bump-semver@v1
+        id: bump-semver
+        if: "! startsWith(github.ref, 'refs/tags')"
+        with:
+          current_version: ${{ steps.get-latest-tag.outputs.tag }}
+          level: patch
 
-    - name: Get the version for merge
-      id: get_version2
-      if: "! startsWith(github.ref, 'refs/tags')"
-      shell: bash 
-      run: |
-        echo "OPERATOR_IMAGE_TAG=latest" >> $GITHUB_ENV
-        echo "BUNDLE_IMAGE_TAG=v0.0.1" >> $GITHUB_ENV
-        echo "BUNDLE_VERSION=0.0.1" >> $GITHUB_ENV 
+      - name: Get the version for push
+        id: get_version2
+        if: "! startsWith(github.ref, 'refs/tags')"
+        shell: bash
+        run: |
+          export BUNDLE_VERSION=${{ steps.bump-semver.outputs.new_version }}
+          echo "OPERATOR_IMAGE_TAG=latest" |tee -a $GITHUB_ENV
+          echo "BUNDLE_IMAGE_TAG=latest" |tee -a $GITHUB_ENV
+          echo "BUNDLE_VERSION=${BUNDLE_VERSION:1}" |tee -a $GITHUB_ENV
 
-    - name: build code
-      run:  make
-      shell: bash
-      
-    - name: build bundle
-      shell: bash 
-      run: |
-        make bundle IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${OPERATOR_IMAGE_TAG} VERSION=${BUNDLE_VERSION} DEFAULT_CHANNEL=alpha
+      - name: build code
+        run: make
+        shell: bash
 
-    - name: verify bundle
-      shell: bash
-      run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
+      - name: build bundle
+        shell: bash
+        run: |
+          make bundle IMG=quay.io/${QUAY_REGISTRY}:${OPERATOR_IMAGE_TAG} VERSION=${BUNDLE_VERSION} DEFAULT_CHANNEL=alpha
 
-    - name: build chart
-      shell: bash
-      run: make helmchart VERSION=${BUNDLE_VERSION} IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${OPERATOR_IMAGE_TAG}      
+      - name: verify bundle
+        shell: bash
+        run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v1
-    
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
-    
-    - name: Login to DockerHub
-      uses: docker/login-action@v1 
-      with:
-        registry: quay.io/${{ github.repository_owner }}
-        username: ${{ secrets.QUAY_USERNAME }}
-        password: ${{ secrets.QUAY_PASSWORD }}      
+      - name: build chart
+        shell: bash
+        run: make helmchart VERSION=${BUNDLE_VERSION} IMG=quay.io/${QUAY_REGISTRY}:${OPERATOR_IMAGE_TAG}
 
-    - name: "Build and Push Operator Image"
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./Dockerfile
-        push: true
-        tags: "quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.OPERATOR_IMAGE_TAG }}"
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
 
-    - name: "Build and Push Bundle Image"
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./bundle.Dockerfile
-        push: true
-        tags: "quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}-bundle:${{ env.BUNDLE_IMAGE_TAG }}" 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-    - name: "Verify bundle image"
-      shell: bash
-      run: operator-sdk bundle validate quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)-bundle:${BUNDLE_IMAGE_TAG} --select-optional name=operatorhub    
-      
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
+        with:
+          registry: quay.io/${{ env.QUAY_REGISTRY }}
+          username: ${{ secrets.QUAY_USERNAME }}
+          password: ${{ secrets.QUAY_PASSWORD }}
+
+      - name: "Build and Push Operator Image"
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: "quay.io/${{ env.QUAY_REGISTRY }}:latest,quay.io/${{ env.QUAY_REGISTRY }}:${{ env.OPERATOR_IMAGE_TAG }}"
+
+      - name: Update CSV
+        env:
+          QUAY_REGISTRY: "${{ env.QUAY_REGISTRY }}"
+          REPOSITORY_NAME: "${{ env.REPOSITORY_NAME }}"
+          OPERATOR_IMAGE_TAG: "${{ env.OPERATOR_IMAGE_TAG }}"
+        run: ./hack/update_csv.sh
+
+      - name: Verify bundle after csv update
+        shell: bash
+        run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
+
+      - name: "Build and Push Bundle Image"
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./bundle.Dockerfile
+          push: true
+          tags: "quay.io/${{ env.QUAY_REGISTRY }}-bundle:latest,quay.io/${{ env.QUAY_REGISTRY }}-bundle:${{ env.BUNDLE_IMAGE_TAG }}"
+
+      - name: "Verify bundle image"
+        shell: bash
+        run: operator-sdk bundle validate quay.io/${QUAY_REGISTRY}-bundle:${BUNDLE_IMAGE_TAG} --select-optional name=operatorhub
+
   release-helm-chart:
-    name: Helm Chart Release      
+    name: Helm Chart Release
     runs-on: ubuntu-latest
     if: "startsWith(github.ref, 'refs/tags')"
     needs: ["build"]
     steps:
-
       - name: set repo name
         shell: bash
-        run: | 
-          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
+        env:
+          QUAY_REGISTRY: ${{ secrets.QUAY_REGISTRY }}
+        run: |
+          DEFAULT_QUAY_REGISTRY=${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)
+          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" |tee -a $GITHUB_ENV
+          echo "QUAY_REGISTRY=${QUAY_REGISTRY:-$DEFAULT_QUAY_REGISTRY}" |tee -a $GITHUB_ENV
 
       - name: Checkout
-        uses: actions/checkout@v2       
-      
+        uses: actions/checkout@v2
+
+      - name: Download compatible Helm version
+        shell: bash
+        env:
+          HELM_VERSION: v3.3.0
+        run: |
+          curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar vxz \
+              && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
+              && rm -vrf linux-amd64
+
       - name: Get the version
         id: get_version
-        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" |tee -a $GITHUB_ENV
 
       - name: Configure Git
         shell: bash
         run: |
           git config --global user.name "$GITHUB_ACTOR"
           git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
-
       - name: checkout gh-pages
         uses: actions/checkout@v2
         with:
@@ -142,11 +198,11 @@ jobs:
 
       - name: Build helm chart repo
         shell: bash
-        run: make helmchart-repo VERSION=${VERSION} IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${version} CHART_REPO_URL=https://${{ github.repository_owner }}.github.io/$(basename $GITHUB_REPOSITORY) HELM_REPO_DEST=./tmp/gh-pages
-      
+        run: make helmchart-repo VERSION=${VERSION} IMG=quay.io/${QUAY_REGISTRY}:${version} CHART_REPO_URL=https://${{ github.repository_owner }}.github.io/$(basename $GITHUB_REPOSITORY) HELM_REPO_DEST=./tmp/gh-pages
+
       - name: push helm repo to gh-pages
         shell: bash
-        run: make helmchart-repo-push VERSION=${VERSION} IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${version} CHART_REPO_URL=https://${{ github.repository_owner }}.github.io/$(basename $GITHUB_REPOSITORY) HELM_REPO_DEST=./tmp/gh-pages
+        run: make helmchart-repo-push VERSION=${VERSION} IMG=quay.io/${QUAY_REGISTRY}:${version} CHART_REPO_URL=https://${{ github.repository_owner }}.github.io/$(basename $GITHUB_REPOSITORY) HELM_REPO_DEST=./tmp/gh-pages
 
   release-github:
     name: GitHub Release
@@ -154,11 +210,10 @@ jobs:
     if: "startsWith(github.ref, 'refs/tags')"
     needs: ["build"]
     steps:
-
       - name: set repo name
         shell: bash
-        run: | 
-          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
+        run: |
+          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" |tee -a $GITHUB_ENV
 
       - name: Checkout
         uses: actions/checkout@v2
@@ -166,7 +221,7 @@ jobs:
           git fetch --prune --unshallow
       - name: Get the version
         id: get_version
-        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" |tee -a $GITHUB_ENV
       - name: Generate Changelog
         run: |
           LATEST_TAG=$(git tag --sort=creatordate | sed '$!d')
@@ -186,18 +241,21 @@ jobs:
           prerelease: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  
+
   release-operatorhub:
     name: Relase to OperatorHub via community-operators (We don't actually commit in this case)
     runs-on: ubuntu-latest
     if: "startsWith(github.ref, 'refs/tags')"
     needs: ["build"]
     steps:
-
       - name: set repo name
         shell: bash
-        run: | 
-          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
+        env:
+          QUAY_REGISTRY: ${{ secrets.QUAY_REGISTRY }}
+        run: |
+          DEFAULT_QUAY_REGISTRY=${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)
+          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" |tee -a $GITHUB_ENV
+          echo "QUAY_REGISTRY=${QUAY_REGISTRY:-$DEFAULT_QUAY_REGISTRY}" |tee -a $GITHUB_ENV
 
       - name: Checkout
         uses: actions/checkout@v2
@@ -209,17 +267,26 @@ jobs:
         shell: bash
         env:
           RELEASE_VERSION: v1.5.0
-        run: | 
+        run: |
           curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
           chmod +x operator-sdk_linux_amd64
           mkdir ${HOME}/bin
           mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
-          echo "${HOME}/bin" >> $GITHUB_PATH
+          echo "${HOME}/bin" |tee -a $GITHUB_PATH
+
+      - name: Install yq
+        shell: bash
+        env:
+          YQ_VERSION: 3.4.0
+        run: |
+          sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
+
       - name: Get the version
         id: get_version
         run: |
           export TAG=${GITHUB_REF/refs\/tags\//}
-          echo "VERSION=${TAG:1}" >> $GITHUB_ENV
+          echo "VERSION=${TAG:1}" |tee -a $GITHUB_ENV
       - name: checkout community-operators
         uses: actions/checkout@v2
         with:
@@ -229,19 +296,22 @@ jobs:
       - name: check whether it is first release
         shell: bash
         run: |
-          echo first_release=$([[ ! -d "./tmp/community-operators/community-operators/$(basename $GITHUB_REPOSITORY)" ]] && echo 'true' || echo 'false') >> $GITHUB_ENV
+          echo first_release=$([[ ! -d "./tmp/community-operators/community-operators/$(basename $GITHUB_REPOSITORY)" ]] && echo 'true' || echo 'false') |tee -a $GITHUB_ENV
           echo $first_release
 
-      
       - name: create and copy bundle to community operators
         shell: bash
-        run: | 
-          make bundle IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):v${VERSION} VERSION=${VERSION} DEFAULT_CHANNEL=alpha
+        env:
+          QUAY_REGISTRY: "${{ env.QUAY_REGISTRY }}"
+          REPOSITORY_NAME: "${{ env.REPOSITORY_NAME }}"
+          OPERATOR_IMAGE_TAG: "v${{ env.VERSION }}"
+        run: |
+          make bundle IMG=quay.io/${QUAY_REGISTRY}:v${VERSION} VERSION=${VERSION} DEFAULT_CHANNEL=alpha
+          ./hack/update_csv.sh
           sed  's/bundle\///g' bundle.Dockerfile > bundle/Dockerfile
           sed -i '/replaces: '"$(basename $GITHUB_REPOSITORY)"'/d' ./bundle/manifests/$(basename $GITHUB_REPOSITORY).clusterserviceversion.yaml
           mkdir -p ./tmp/community-operators/community-operators/$(basename $GITHUB_REPOSITORY)/${VERSION}
           /bin/cp -v -R ./bundle/* ./tmp/community-operators/community-operators/$(basename $GITHUB_REPOSITORY)/${VERSION}
-          /bin/cp -v -R ./config/community-operators/* ./tmp/community-operators/community-operators/$(basename $GITHUB_REPOSITORY)         
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v3
@@ -249,8 +319,8 @@ jobs:
         with:
           path: ./tmp/community-operators
           commit-message: ${{ env.REPOSITORY_NAME }} release ${{ env.VERSION }}
-          committer: ${{ github.actor }} <raffaele.spazzoli@gmail.com>
-          author: ${{ github.actor }} <raffaele.spazzoli@gmail.com>
+          committer: ${{ github.actor }} <andy.block@gmail.com>
+          author: ${{ github.actor }} <andy.block@gmail.com>
           signoff: true
           branch: ${{ env.REPOSITORY_NAME }}-${{ env.VERSION }}
           delete-branch: true
@@ -309,12 +379,12 @@ jobs:
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v3
-        if: ${{ ! startsWith( env.first_release, 'true' ) }} 
+        if: ${{ ! startsWith( env.first_release, 'true' ) }}
         with:
           path: ./tmp/community-operators
           commit-message: ${{ env.REPOSITORY_NAME }} release ${{ env.VERSION }}
-          committer: ${{ github.actor }} <raffaele.spazzoli@gmail.com>
-          author: ${{ github.actor }} <raffaele.spazzoli@gmail.com>
+          committer: ${{ github.actor }} <andy.block@gmail.com>
+          author: ${{ github.actor }} <andy.block@gmail.com>
           signoff: true
           branch: ${{ env.REPOSITORY_NAME }}-${{ env.VERSION }}
           delete-branch: true
@@ -369,6 +439,5 @@ jobs:
             <sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file a PR against this repo and explain your need
 
             <sup>2</sup> For more information see [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.svg)
-          token:  ${{ secrets.COMMUNITY_OPERATOR_PAT }}         
-     
+          token: ${{ secrets.COMMUNITY_OPERATOR_PAT }}
 
