Add new github action

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -106,6 +106,12 @@ jobs:
         shell: bash
         run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
 
+      - name: process bundle for disconnected support
+        uses: redhat-cop/github-actions/disconnected-csv@main
+        with:
+          CSV_FILE: bundle/manifests/namespace-configuration-operator.clusterserviceversion.yaml
+          TAGS_TO_DIGESTS: ${OPERATOR_IMAGE_TAG}
+
       - name: build chart
         shell: bash
         run: make helmchart VERSION=${BUNDLE_VERSION} IMG=quay.io/${QUAY_REGISTRY}:${OPERATOR_IMAGE_TAG}
@@ -154,6 +160,102 @@ jobs:
         shell: bash
         run: operator-sdk bundle validate quay.io/${QUAY_REGISTRY}-bundle:${BUNDLE_IMAGE_TAG} --select-optional name=operatorhub
 
+    - name: set repo name
+      shell: bash
+      run: | 
+        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV    
+
+    - name: Set up Go 1.x
+      uses: actions/setup-go@v2
+      with:
+        go-version: ^1.16
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
+    - name: Download operator sdk
+      shell: bash
+      env:
+        RELEASE_VERSION: v1.9.0
+      run: | 
+        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
+        chmod +x operator-sdk_linux_amd64
+        mkdir ${HOME}/bin
+        mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
+        echo "${HOME}/bin" >> $GITHUB_PATH
+
+    - name: Get the version for tags
+      id: get_version1
+      if: "startsWith(github.ref, 'refs/tags')"
+      shell: bash
+      run: |
+        echo "OPERATOR_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+        echo "BUNDLE_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+        export TAG=${GITHUB_REF/refs\/tags\//}
+        echo "BUNDLE_VERSION=${TAG:1}" >> $GITHUB_ENV
+        export SEMVER_COMPLIANT=$(echo ${TAG:1} | egrep '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-])(?:\.(?:0|[1-9]\d|\d*[a-zA-Z-][0-9a-zA-Z-]))))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')
+        if [ -z "$SEMVER_COMPLIANT" ]; then   echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}"; exit 1; fi
+
+
+
+    - name: Get the version for merge
+      id: get_version2
+      if: "! startsWith(github.ref, 'refs/tags')"
+      shell: bash 
+      run: |
+        echo "OPERATOR_IMAGE_TAG=latest" >> $GITHUB_ENV
+        echo "BUNDLE_IMAGE_TAG=v0.0.1" >> $GITHUB_ENV
+        echo "BUNDLE_VERSION=0.0.1" >> $GITHUB_ENV 
+
+    - name: build code
+      run:  make
+      shell: bash
+      
+    - name: build bundle
+      shell: bash 
+      run: |
+        make bundle IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${OPERATOR_IMAGE_TAG} VERSION=${BUNDLE_VERSION} DEFAULT_CHANNEL=alpha
+
+    - name: verify bundle
+      shell: bash
+      run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
+
+    - name: build chart
+      shell: bash
+      run: make helmchart VERSION=${BUNDLE_VERSION} IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):${OPERATOR_IMAGE_TAG}      
+
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v1
+    
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
+    
+    - name: Login to DockerHub
+      uses: docker/login-action@v1 
+      with:
+        registry: quay.io/${{ github.repository_owner }}
+        username: ${{ secrets.QUAY_USERNAME }}
+        password: ${{ secrets.QUAY_PASSWORD }}      
+
+    - name: "Build and Push Operator Image"
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./Dockerfile
+        push: true
+        tags: "quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.OPERATOR_IMAGE_TAG }}"
+
+    - name: "Build and Push Bundle Image"
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./bundle.Dockerfile
+        push: true
+        tags: "quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}-bundle:${{ env.BUNDLE_IMAGE_TAG }}" 
+
+    - name: "Verify bundle image"
+      shell: bash
+      run: operator-sdk bundle validate quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)-bundle:${BUNDLE_IMAGE_TAG} --select-optional name=operatorhub    
+      
   release-helm-chart:
     name: Helm Chart Release
     runs-on: ubuntu-latest
@@ -262,12 +364,12 @@ jobs:
       - name: Set up Go 1.x
         uses: actions/setup-go@v2
         with:
-          go-version: ^1.14
+          go-version: ^1.16
       - name: Download operator sdk
         shell: bash
         env:
-          RELEASE_VERSION: v1.5.0
-        run: |
+          RELEASE_VERSION: v1.9.0
+        run: | 
           curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
           chmod +x operator-sdk_linux_amd64
           mkdir ${HOME}/bin
